import { Brand } from "@/types/brand";

const brandData: Brand[] = [
  {
    id: 1,
    name: "Client",
    href: "#",
    image: "/images/brand/alpharithm.png",
    imageLight: "/images/brand/alpharithm.png",
  },
  {
    id: 2,
    name: "Client",
    href: "#",
    image: "/images/brand/AP&T.png",
    imageLight: "/images/brand/AP&T.png",
  },
  {
    id: 3,
    name: "Client",
    href: "#",
    image: "/images/brand/Aptean.png",
    imageLight: "/images/brand/Aptean.png",
  },
  {
    id: 4,
    name: "Client",
    href: "#",
    image: "/images/brand/CRI.png",
    imageLight: "/images/brand/CRI.png",
  },
  {
    id: 5,
    name: "Client",
    href: "#",
    image: "/images/brand/Fomra.png",
    imageLight: "/images/brand/Fomra.png",
  },
  {
    id: 6,
    name: "Client",
    href: "#",
    image: "/images/brand/gunung steel.png",
    imageLight: "/images/brand/gunung steel.png",
  },
  {
    id: 7,
    name: "Client",
    href: "#",
    image: "/images/brand/gympac.png",
    imageLight: "/images/brand/gympac.png",
  },
  {
    id: 8,
    name: "Client",
    href: "#",
    image: "/images/brand/hinduja tech.png",
    imageLight: "/images/brand/hinduja tech.png",
  },
  {
    id: 9,
    name: "Client",
    href: "#",
    image: "/images/brand/Infosight consulting.png",
    imageLight: "/images/brand/Infosight consulting.png",
  },
  {
    id: 10,
    name: "Client",
    href: "#",
    image: "/images/brand/life cell.png",
    imageLight: "/images/brand/life cell.png",
  },
  {
    id: 11,
    name: "Client",
    href: "#",
    image: "/images/brand/NSK.png",
    imageLight: "/images/brand/NSK.png",
  },
  {
    id: 12,
    name: "Client",
    href: "#",
    image: "/images/brand/PKF.png",
    imageLight: "/images/brand/PKF.png",
  },
  {
    id: 13,
    name: "Client",
    href: "#",
    image: "/images/brand/Psiog Digital.png",
    imageLight: "/images/brand/Psiog Digital.png",
  },
  {
    id: 14,
    name: "Client",
    href: "#",
    image: "/images/brand/quadrant.png",
    imageLight: "/images/brand/quadrant.png",
  },
  {
    id: 15,
    name: "Client",
    href: "#",
    image: "/images/brand/Quiz Infomatics.png",
    imageLight: "/images/brand/Quiz Infomatics.png",
  },
  {
    id: 16,
    name: "Client",
    href: "#",
    image: "/images/brand/saraswathy school.png",
    imageLight: "/images/brand/saraswathy school.png",
  },
  {
    id: 17,
    name: "Client",
    href: "#",
    image: "/images/brand/SIS.png",
    imageLight: "/images/brand/SIS.png",
  },
  {
    id: 18,
    name: "Client",
    href: "#",
    image: "/images/brand/Smartstatz.png",
    imageLight: "/images/brand/Smartstatz.png",
  },
  {
    id: 19,
    name: "Client",
    href: "#",
    image: "/images/brand/Sundaram Infotech.png",
    imageLight: "/images/brand/Sundaram Infotech.png",
  },
  {
    id: 20,
    name: "Client",
    href: "#",
    image: "/images/brand/union insurance.png",
    imageLight: "/images/brand/union insurance.png",
  },
];

export default brandData;
